CREATE DATABASE ECOMMERCE_AND_RETAIL_SUPPLY_CHAIN;
use  ECOMMERCE_AND_RETAIL_SUPPLY_CHAIN;
-- WHAT IS TOTAL REVENUE GENERATED
SELECT ROUND(SUM(NET_REVENUE),2)AS TOTAL_REVENUE
FROM SALES_CLEANED;
-- HOW MANY TOTAL ORDERS ARE THERE IN THE DATASET
SELECT COUNT(DISTINCT ORDER_ID)AS TOTAL_ORDERS
FROM SALES_CLEANED;
-- TOP 10 BEST SELLING PRODUCTS BY QUANTITY
SELECT P.PRODUCT_NAME, SUM(S.QUANTITY)AS UNITS_SOLD
FROM SALES_CLEANED S
JOIN PRODUCT_CLEANED P 
ON S.SKU_ID=P.SKU_ID
GROUP BY P.PRODUCT_NAME
ORDER BY UNITS_SOLD DESC
LIMIT 10;
-- HOW MANY TOTAL UNITS ARE SOLD
SELECT SUM(QUANTITY)AS TOTAL_UNITS_SOLD
FROM SALES_CLEANED;
-- TOP 10 REVENUE GENERATING PRODUCTS
SELECT P.PRODUCT_NAME,ROUND(SUM(S.NET_REVENUE),2)AS TOTAL_REVENUE
FROM SALES_CLEANED S
JOIN PRODUCT_CLEANED P 
ON S.SKU_ID=P.SKU_ID
GROUP BY P.PRODUCT_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 10;
-- SHOW REVENUE BY BRAND
SELECT P.BRAND, ROUND(SUM(S.NET_REVENUE),2)AS TOTAL_REVENUE
FROM SALES_CLEANED S
JOIN PRODUCT_CLEANED P
ON S.SKU_ID=P.SKU_ID
GROUP BY P.BRAND
ORDER BY TOTAL_REVENUE DESC;
-- SHOW REVENUE BY CATEGORY
SELECT P.CATEGORY, ROUND(SUM(S.NET_REVENUE),2)AS TOTAL_REVENUE
FROM SALES_CLEANED S
JOIN PRODUCT_CLEANED P
ON S.SKU_ID=P.SKU_ID
GROUP BY P.CATEGORY
ORDER BY TOTAL_REVENUE DESC;
-- SHOW MONTHLY REVENUE TREND
SELECT MONTH,ROUND(SUM(NET_REVENUE),2)AS REVENUE
FROM SALES_CLEANED
GROUP BY MONTH 
ORDER BY MONTH;
-- SHOW CHANNEL PERFORMANCE
SELECT CHANNEL, ROUND(SUM(NET_REVENUE),2)AS REVENUE
FROM SALES_CLEANED
GROUP BY CHANNEL
ORDER BY REVENUE DESC;
-- SHOW AVERAGE PRODUCT RATING BY CATEGORY
SELECT CATEGORY,ROUND(AVG(AVG_RATING),2)AS AVG_RATING
FROM PRODUCT_CLEANED
GROUP BY CATEGORY;
-- SHOW PRODUCTS WITH LOW INVENTORY
SELECT SKU_ID, CURRENT_STOCK
FROM INVENTORY_SNAPSHOT_CLEANED
WHERE CURRENT_STOCK < REORDER_POINT;
-- SHOW PRODUCTS WITH HIGHEST CURRENT STOCK
SELECT SKU_ID, CURRENT_STOCK
FROM INVENTORY_SNAPSHOT_CLEANED
ORDER BY CURRENT_STOCK DESC
LIMIT 10;
-- SHOW SUPPLIER WISE PURCHASE QUANTITY
SELECT SUPPLIER_ID, SUM(ORDER_QTY)AS TOTAL_ORDERED
FROM PURCHASE_ORDERS_CLEANED
GROUP BY SUPPLIER_ID
ORDER BY TOTAL_ORDERED DESC;
-- SHOW PURCHASE COST BY SUPPLIER
SELECT SUPPLIER_ID, ROUND(SUM(UNIT_COST),2)AS PURCHASE_COST
FROM PURCHASE_ORDERS_CLEANED
GROUP BY SUPPLIER_ID
ORDER BY PURCHASE_COST DESC;
-- SHOW REVENUE BY CUSTOMER SEGMENT
SELECT CUSTOMER_SEGMENT, ROUND(SUM(NET_REVENUE),2)AS REVENUE
FROM SALES_CLEANED
GROUP BY CUSTOMER_SEGMENT
ORDER BY REVENUE DESC;
-- SHOW REVENUE BY DEVICE TYPE
SELECT DEVICE_TYPE, ROUND(SUM(NET_REVENUE),2)AS REVENUE
FROM SALES_CLEANED
GROUP BY DEVICE_TYPE
ORDER BY REVENUE DESC;
-- SHOW RETURN ANALYSIS
SELECT RETURNED_FLAG, COUNT(*) AS ORDERS
FROM SALES_CLEANED
GROUP BY RETURNED_FLAG;
-- SHOW REVENUE LOST DUE TO RETURNS
SELECT ROUND(SUM(NET_REVENUE),2)
FROM SALES_CLEANED
WHERE RETURNED_FLAG=1;
-- SHOW TOP SUPPLIERS BY PRODUCT COUNT
SELECT S.SUPPLIER_NAME, COUNT(P.SKU_ID)AS PRODUCT_COUNT
FROM SUPPLIERS_CLEANED S 
JOIN PRODUCT_CLEANED P 
ON S.SUPPLIER_ID=P.PRIMARY_SUPPLIER_ID
GROUP BY S.SUPPLIER_NAME
ORDER BY PRODUCT_COUNT DESC;








